[package]
name = "cairo"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
sonic-rs = "0.5.1"

cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "4bf779d" }
cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "227c482" }
cairo-prove = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "4bf779d" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "3327027", features = [
  "mod_builtin",
] }
stwo_cairo_prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "4bf779d" }

utils = { path = "../utils" }
dotenv = "0.15.0"
