[package]
name = "cairo"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
sonic-rs = "0.5.1"
log = "0.4"
regex = "1.10"

cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "92232543984e20e984c5a7194561ff1fffa76dae" }
cairo-prove = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "92232543984e20e984c5a7194561ff1fffa76dae"}
stwo_cairo_prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "92232543984e20e984c5a7194561ff1fffa76dae" }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "92232543984e20e984c5a7194561ff1fffa76dae" }

cairo-lang-runner = { git = "https://github.com/starkware-libs/cairo.git", rev = "b59953c3f20be94a416ffd95b9f89c037ee63ec7" }
cairo-lang-casm = { git = "https://github.com/starkware-libs/cairo.git", rev = "b59953c3f20be94a416ffd95b9f89c037ee63ec7" }
cairo-lang-utils = { git = "https://github.com/starkware-libs/cairo.git", rev = "b59953c3f20be94a416ffd95b9f89c037ee63ec7" }
cairo-lang-executable = { git = "https://github.com/starkware-libs/cairo.git", rev = "b59953c3f20be94a416ffd95b9f89c037ee63ec7" }

cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", rev = "e2c6c91c73cd0bc351721f302390fcc0965c6224", features = [
  "mod_builtin",
] }

utils = { path = "../utils" }
dotenv = "0.15.0"
