[package]
name = "fibonacci-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.2.0" }
guests = { path = "../../guests", features = ["fibonacci"] }

[features]
default = []
std = ["openvm/std"]
