[package]
version = "0.1.0"
name = "host"
edition = "2024"

[dependencies]
sp1-sdk = { workspace = true, features = ["profiling"] }
dotenv = { workspace = true }
utils = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
