[package]
name = "cairo-zero"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
sonic-rs = "0.5.1"
serde_json = "1.0"

cairo-air = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "4bf779d8448e1eae2a8f5ffcfd0d4b3a1e879bd1" }
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", tag = "v3.0.1", features = [
  "mod_builtin",
] }
stwo-cairo-adapter = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "4bf779d8448e1eae2a8f5ffcfd0d4b3a1e879bd1" }
stwo_cairo_prover = { git = "https://github.com/starkware-libs/stwo-cairo", rev = "4bf779d8448e1eae2a8f5ffcfd0d4b3a1e879bd1" }

utils = { path = "../utils" }
dotenv = "0.15.0"
regex = "1.11.2"
