[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
serde = "1.0.197"
serde_with = "3.8"
serde_json = { version = "1.0" }
tabled = "0.15"
csv = "1.1"
human-repr = { version = "1.0", features = ["1024"] }
hex = "0.4.3"
k256 = { version = "=0.13.4", features = [
  "arithmetic",
  "serde",
  "expose-field",
  "std",
  "ecdsa",
], default-features = false }
guests = { path = "../guests", features = ["with-ecdsa"] }
pprof = { version = "0.14.0", features = ["prost-codec"] }
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.18"
rand = "0.8"
libc = "0.2"
