[package]
name = "cairo-m"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-m-common = { git = "https://github.com/kkrt-labs/cairo-m", branch = "main" }
cairo-m-runner = { git = "https://github.com/kkrt-labs/cairo-m", branch = "main" }
cairo-m-prover = { git = "https://github.com/kkrt-labs/cairo-m", branch = "main" }
cairo-m-compiler = { git = "https://github.com/kkrt-labs/cairo-m", branch = "main" }
dotenv = "0.15.0"
sha2 = "0.10"
sonic-rs = "0.5.2"
stwo-prover = { git = "https://github.com/starkware-libs/stwo", features = [
  "parallel",
], tag = "v1.0.0" }
thiserror = "2.0.12"
utils = { path = "../utils" }

[patch."https://github.com/HorizenLabs/poseidon2.git"]
zkhash = { git = "https://github.com/AntoineFONDEUR/poseidon2.git", branch = "poseidon2-M31" }
