[package]
name = "valida-bench-host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fibonacci"
path = "src/bin/fibonacci.rs"

[[bin]]
name = "sha2"
path = "src/bin/sha2.rs"

[dependencies]
tempfile = "3.10.1"
utils = { path = "../../utils" }
[target.'cfg(target_arch = "x86_64")'.dependencies]
valida-vm-api-linux-x86 = "0.10.0"
[target.'cfg(target_arch = "aarch64")'.dependencies]
valida-vm-api-linux-arm = "0.10.0"
